version: '2'
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_USER: boilerplate
      POSTGRES_PASSWORD: boilerplate
    logging:
      driver: "none"
    volumes:
      - boilerplate_pgdata:/var/lib/postgresql/data
  boilerplate:
    build: .
    entrypoint:
      - /app/server.sh
    restart: unless-stopped
    links:
      - "postgres"
    ports:
      - "4001:4001"
    depends_on:
      - "postgres"
    environment:
      GO3_DB_DATABASE: boilerplate
      GO3_DB_USER: boilerplate
      GO3_DB_PASSWORD: boilerplate
      GO3_DB_HOST: postgres
      GO3_DB_LOGGING: "false"
      GO3_DB_DRIVER: postgres

volumes:
  boilerplate_pgdata:
